### ISSUE TITLE
The order list with index error

### ISSUE THREAD

**Issue by FerrisLee-180505** [Rosey/markdown-draft-js#127]
**Do you want to request a *feature* or report a *bug*?**

I think is a **bug**

**What is the current behavior?**

the order list with error-index when inserting some text into 2 order list.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. You can use this jsfiddle to get started: https://jsfiddle.net/gmertk/e61z7nfa/.**

the demo link: http://www.roserobertson.me/markdown-draft-js/
To Test:

1. Enter some text between the two OrderLists

there are some videos and screenshots for regression.  The following:
![image](https://user-images.githubusercontent.com/54788131/85940643-28211380-b950-11ea-9d55-ae626a2067e8.png)

![markdown-draft-js](https://user-images.githubusercontent.com/54788131/85940795-3885be00-b951-11ea-95f0-dc162458aaf3.gif)

**What is the expected behavior?**

With correct index

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**

Chrome Version 79.0.3945.88 (Official B

uild) (32-bit)

**Comment by Rosey** [comment]
Thanks very much for this report! I'll take a look when I have a chance 😊

**Comment by alibosworth** [comment]
Also running into this on a project called **Flow**, it appears to have been solved [here](https://github.com/Rosey/markdown-draft-js/pull/135), though no coverage has been added for it.  I'll look at adding that.

**Comment by Rosey** [comment]
Merged into main, still need to publish a new release with the fix
