### ISSUE TITLE
Documentation is unclear about collapsing newlines

### ISSUE THREAD

**Issue by alibosworth** [Rosey/markdown-draft-js#142]
I'm finding it hard to understand this:

>preserveNewlines can be passed in to preserve empty whitespace newlines. By default, markdown rules specify that blank whitespace is collapsed, but in the interest in maintaining 1:1 parity with draft appearance-wise, this option can be turned on if you like :)

Does collapsing newlines mean that only a max of one empty line is kept (two new-line characters are retained when there are many new-line characters) or that NO empty line is kept (only one new-line character is ever kept)

**Comment by Rosey** [comment]
❤️
