### ISSUE TITLE
Strikethrough conversion is incomplete

### ISSUE THREAD

**Issue by tobiaspatton-s4** [Rosey/markdown-draft-js#156]
`markdownToDraft(string, options)` includes support for writing markdown with strikethrough text enclosed with  `~~` but `draftToMarkdown(rawDraftObject, options)` does not include support for creating a DraftJS inline style when the `~~` marker is encountered. 

It's possible to add a custom entry to BlockStyles when invoking the conversion routine, but since default support is included in one direction, it makes sense to support it in the other direction as well.

I'll create a PR for this issue.

**Comment by Rosey** [comment]
Thanks for your PR 🙂 merged it and will close this!
