### ISSUE TITLE
Outputs incorrect markdown

### ISSUE THREAD

**Issue by Jpunt** [Rosey/markdown-draft-js#28]
When the user has bold enabled and starts typing, this will result in invalid markdown every time the user types a space:

```
some words before bold, **some words in bold **and some words after bold
```

Because the space after the word "bold" is before the two stars instead of after them, this will result in a plain text (containing the actual stars).

**Comment by Rosey** [comment]
Interesting, this is an issue I'm aware of and have commented on before in code. I actually thought there was a work-around in place for it already but I'll take a look, because it's clearly not working!

**Comment by Rosey** [comment]
Wait, is this when converting draft to markdown or vice versa? Because I just added some tests and it _is_ working when converting draft to markdown which I thought was the case you were talking about here? I did add a pr with some changes to how it works to handle more tabs and stuff but this basic case I think did already work properly?

**Comment by Jpunt** [comment]
Yeah, that is exactly what I mean 🤔 Your test looks great. But the issue seems to be apparent still. You can also see it in the [demo](https://rosey.github.io/markdown-draft-js/). Enable bold, type `test ` and see the result `**test **`. Right?

Wait, I guess my example was wrong! Sorry about that 😄 When there's text after the bold part, the space gets fixed (which is your test 👍), but as long as there's nothing after the bold part and the space, the space remains inside the bold part (like just and only the value `test `).

**Comment by Rosey** [comment]
Ah ok thanks for the additional info! I'll add some tests for that situation as well and make sure my latest PR handles those cases :)

**Comment by Rosey** [comment]
Fix just got merged - https://github.com/Rosey/markdown-draft-js/pull/31

And I have filed a separate issue to get fixed for a very similar bug: https://github.com/Rosey/markdown-draft-js/issues/32

Will do a bug fix release soon.
