### ISSUE TITLE
A few updates

### ISSUE THREAD

**Issue by atanasster** [Rosey/markdown-draft-js#34]
Hi Rosey,

I sent a few updates via email if you would like to incorporate, and just so you know its not spam, I am also writing here

- Added support for Images
- Added support for UNDERLINE, SUBSCRIPT, SUPERSCRIPT
- Added support for custom inline styles (currently color, background color) - rendered as <span elements for markdown
- Enabled html tag remarkable handling (for the above need to embed html tags such as span)
- Allowing for custom html block and inline style entities for end-users
- Fixed embedding styles for example ***BOLD AND ITALIC - previously the markdown-to-draft was not adjusting correctly the length of the inline style

https://www.dropbox.com/s/65t2k8c1lpmfn6h/Archive.zip

**Comment by husseinbob** [comment]
> Added support for UNDERLINE, SUBSCRIPT, SUPERSCRIPT
> Just going to close this as there's a pull request with these changes and further discussion

I don't see any reference to UNDERLINE in the code...
