### ISSUE TITLE
blank newlines in markdown don't convert to draft the same way as they do to markdown

### ISSUE THREAD

**Issue by Rosey** [Rosey/markdown-draft-js#37]
If you check out the example, when you modify the textarea, a newline always only counts as 1, even if you have 3 in a row.

But when you modify the draft editor, each newline is converted 1:1 to markdown. This behaviour is more desireable than the markdown-to-draft behaviour!

**Comment by Rosey** [comment]
I guess this is basically because of markdown syntax rules so it is "correct" although it feels whacky.

I'm going to pull request an option where users can enable non-collapsing whitespace if they so desire.

**Comment by Rosey** [comment]
Sorry I have a branch that does this but I'm still conflicted over whether this should even be an option since it kind of skews the rules of markdown, so I haven't PR'd it yet. So lmk if you're waiting on this or really want it!

**Comment by juliankrispel** [comment]
@Rosey I totally need/want this :D - or a client does, would be happy to help get it in :heart:

**Comment by juliankrispel** [comment]
sweeeeet thank you @Rosey 👍 👍 👍

**Comment by Rosey** [comment]
Let me know if you encounter any weirdness with it! Fingers crossed that is is bug free 🤞 😁

**Comment by juliankrispel** [comment]
@Rosey if there is I'll make a pr ✌️

**Comment by juliankrispel** [comment]
this is so perfectly on time btw 😍
