### ISSUE TITLE
Unnecessary hash symbol escape

### ISSUE THREAD

**Issue by igorlesnenko** [Rosey/markdown-draft-js#61]
`#hashtag` is not considered as heading in markdown, as there is no space after `#`.
We should not escape it like this: `\#hashtag`, when converting from DraftJS to markdown.

https://spec.commonmark.org/0.28/#example-34

**Comment by Rosey** [comment]
I've merged a fix for this, will get out a release shortly!

**Comment by igorlesnenko** [comment]
@Rosey I see the issue still exists in 1.1.1

**Comment by igorlesnenko** [comment]
If the line starts from the `#hashtag` it got escaped.
If `word #hashtag` it is ok

**Comment by Rosey** [comment]
argh, just looking

**Comment by Rosey** [comment]
Ugh, `>Test` <-- this needs to be escaped, `#Test` <- this does not. Thank you markdown.

**Comment by Rosey** [comment]
https://github.com/Rosey/markdown-draft-js/pull/72
