### ISSUE TITLE
Is it possible to ignore certain tags

### ISSUE THREAD

**Issue by glitchperfect** [Rosey/markdown-draft-js#91]
I'm trying to exclude the conversion of links and images when converting from markdown to raw. Is there a settings flag I can set to disable it? Or maybe in the remark config?

Thank you for your work, the plugin is really handy

**Comment by Rosey** [comment]
Yes, check out the remarkable config here - https://github.com/jonschlinkert/remarkable under `disable` 😄 hope that helps!
